# Generated by Django 3.1.3 on 2021-01-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='bullets',
            field=models.TextField(default='null', null=True),
        ),
    ]
