# Generated by Django 3.1.3 on 2020-12-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='programme',
            old_name='type',
            new_name='category',
        ),
    ]
