# Generated by Django 3.1.3 on 2020-12-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='item_type',
            field=models.CharField(blank=True, default='programme', max_length=20, null=True),
        ),
    ]
