# Generated by Django 3.1.3 on 2020-12-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_auto_20201219_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='category',
        ),
        migrations.AddField(
            model_name='programme',
            name='category',
            field=models.ManyToManyField(to='programmes.Category'),
        ),
    ]
