# Generated by Django 3.1.3 on 2021-01-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_programme_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
