# Generated by Django 3.1.3 on 2021-01-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_auto_20210112_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
