# Generated by Django 3.1.3 on 2021-01-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_auto_20210114_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='item_type',
        ),
    ]
