# Generated by Django 3.1.3 on 2021-01-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_auto_20210104_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='bullets',
            field=models.TextField(null=True),
        ),
    ]
