# Generated by Django 3.1.3 on 2021-01-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0004_remove_programme_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='discontinued',
            field=models.BooleanField(default=False),
        ),
    ]
