# Generated by Django 3.1.3 on 2021-01-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0005_programme_discontinued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='bullets',
            field=models.TextField(blank=True, null=True),
        ),
    ]
