# Generated by Django 3.1.3 on 2020-12-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20201212_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='description',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='email',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
        migrations.AddField(
            model_name='discussion',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
