# Generated by Django 3.1.3 on 2020-12-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20201212_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='post',
            new_name='forum',
        ),
    ]
