# Generated by Django 3.1.3 on 2020-12-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20201212_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
