# Generated by Django 3.1.3 on 2021-01-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20210112_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_on']},
        ),
    ]
