# Generated by Django 3.1.3 on 2020-12-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20201212_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={},
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='created_on',
            new_name='date_responded',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='created_on',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='active',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='slug',
        ),
        migrations.AddField(
            model_name='forum',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forum'),
        ),
    ]
