# Generated by Django 3.1.3 on 2020-12-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20201213_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='topic',
        ),
    ]
