# Generated by Django 3.1.3 on 2021-01-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_references'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
