# Generated by Django 3.1.3 on 2020-12-31 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_programme_item_type'),
        ('checkout', '0002_auto_20201230_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgOrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proglineitems', to='checkout.order')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.programme')),
            ],
        ),
    ]
