# Generated by Django 3.1.3 on 2021-01-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20210110_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
