# Generated by Django 3.1.3 on 2021-01-20 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0005_programme_discontinued'),
        ('products', '0006_product_discontinued'),
        ('checkout', '0008_auto_20210113_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AlterField(
            model_name='progorderlineitem',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programmes.programme'),
        ),
    ]
