# Generated by Django 3.1.3 on 2021-01-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210113_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_type',
        ),
    ]
