# Generated by Django 3.1.3 on 2021-01-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
